apiVersion: spex.suite.v0.1
kind: ScenarioSuite
metadata:
  name: custom-bundle-git
spec:
  bindingRef: ../bindings/custom-local.yaml
  bundleRefs:
    - name: custom
      version: 0.1.0
      source: git::https://github.com/pruefwerk/spex-bundles.git//custom-echo@v0.1.0
  scenarios:
    - ../providers/custom/custom-echo.yaml
  workspaceDir: ../generated/custom-bundle-git
